# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab3_constraints.xdc

# Block Designs: bd/lab2_simple_arm/lab2_simple_arm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm || ORIG_REF_NAME==lab2_simple_arm}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_processing_system7_0_0/lab2_simple_arm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_processing_system7_0_0 || ORIG_REF_NAME==lab2_simple_arm_processing_system7_0_0}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_0/lab2_simple_arm_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_axi_gpio_0_0 || ORIG_REF_NAME==lab2_simple_arm_axi_gpio_0_0}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_ps7_0_axi_periph_0/lab2_simple_arm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab2_simple_arm_ps7_0_axi_periph_0}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_rst_ps7_0_100M_0/lab2_simple_arm_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab2_simple_arm_rst_ps7_0_100M_0}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_axi_gpio_0_1/lab2_simple_arm_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_axi_gpio_0_1 || ORIG_REF_NAME==lab2_simple_arm_axi_gpio_0_1}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_xbar_0 || ORIG_REF_NAME==lab2_simple_arm_xbar_0}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_led_ip_0_1/lab2_simple_arm_led_ip_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_led_ip_0_1 || ORIG_REF_NAME==lab2_simple_arm_led_ip_0_1}]

# IP: bd/lab2_simple_arm/ip/lab2_simple_arm_auto_pc_0/lab2_simple_arm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_simple_arm_auto_pc_0 || ORIG_REF_NAME==lab2_simple_arm_auto_pc_0}]

# XDC: bd/lab2_simple_arm/lab2_simple_arm_ooc.xdc
