// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir,hls_ip_2016_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.430000,HLS_SYN_LAT=15,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=44,HLS_SYN_FF=977,HLS_SYN_LUT=254}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y,
        y_ap_vld,
        c_address0,
        c_ce0,
        c_q0,
        x,
        x_ap_vld
);

parameter    ap_ST_fsm_state1 = 16'b1;
parameter    ap_ST_fsm_state2 = 16'b10;
parameter    ap_ST_fsm_state3 = 16'b100;
parameter    ap_ST_fsm_state4 = 16'b1000;
parameter    ap_ST_fsm_state5 = 16'b10000;
parameter    ap_ST_fsm_state6 = 16'b100000;
parameter    ap_ST_fsm_state7 = 16'b1000000;
parameter    ap_ST_fsm_state8 = 16'b10000000;
parameter    ap_ST_fsm_state9 = 16'b100000000;
parameter    ap_ST_fsm_state10 = 16'b1000000000;
parameter    ap_ST_fsm_state11 = 16'b10000000000;
parameter    ap_ST_fsm_state12 = 16'b100000000000;
parameter    ap_ST_fsm_state13 = 16'b1000000000000;
parameter    ap_ST_fsm_state14 = 16'b10000000000000;
parameter    ap_ST_fsm_state15 = 16'b100000000000000;
parameter    ap_ST_fsm_state16 = 16'b1000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv64_A = 64'b1010;
parameter    ap_const_lv64_9 = 64'b1001;
parameter    ap_const_lv64_8 = 64'b1000;
parameter    ap_const_lv64_7 = 64'b111;
parameter    ap_const_lv64_6 = 64'b110;
parameter    ap_const_lv64_5 = 64'b101;
parameter    ap_const_lv64_4 = 64'b100;
parameter    ap_const_lv64_3 = 64'b11;
parameter    ap_const_lv64_2 = 64'b10;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_D = 32'b1101;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] y;
output   y_ap_vld;
output  [3:0] c_address0;
output   c_ce0;
input  [31:0] c_q0;
input  [31:0] x;
input   x_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ap_vld;
reg[3:0] c_address0;
reg c_ce0;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [31:0] x_preg;
reg  signed [31:0] x_in_sig;
reg    x_ap_vld_preg;
reg    x_ap_vld_in_sig;
reg  signed [31:0] shift_reg_9;
reg  signed [31:0] shift_reg_8;
reg  signed [31:0] shift_reg_7;
reg  signed [31:0] shift_reg_6;
reg  signed [31:0] shift_reg_5;
reg  signed [31:0] shift_reg_4;
reg  signed [31:0] shift_reg_3;
reg  signed [31:0] shift_reg_2;
reg  signed [31:0] shift_reg_1;
reg  signed [31:0] shift_reg_0;
reg    x_blk_n;
wire   [0:0] ap_CS_fsm_state13;
reg  signed [31:0] reg_188;
wire   [0:0] ap_CS_fsm_state2;
wire   [0:0] ap_CS_fsm_state6;
wire   [0:0] ap_CS_fsm_state9;
wire   [0:0] ap_CS_fsm_state12;
reg  signed [31:0] reg_192;
wire   [0:0] ap_CS_fsm_state3;
wire   [0:0] ap_CS_fsm_state7;
reg  signed [31:0] reg_196;
wire   [0:0] ap_CS_fsm_state4;
wire   [0:0] ap_CS_fsm_state10;
reg  signed [31:0] reg_200;
wire   [0:0] ap_CS_fsm_state5;
wire   [0:0] ap_CS_fsm_state11;
wire   [31:0] grp_fu_208_p2;
reg   [31:0] tmp_6_reg_451;
wire   [31:0] grp_fu_224_p2;
reg   [31:0] tmp_6_1_reg_456;
wire   [31:0] tmp1_fu_278_p2;
reg   [31:0] tmp1_reg_486;
reg  signed [31:0] c_load_6_reg_491;
wire   [0:0] ap_CS_fsm_state8;
wire   [31:0] grp_fu_240_p2;
reg   [31:0] tmp_6_2_reg_501;
wire   [31:0] grp_fu_256_p2;
reg   [31:0] tmp_6_3_reg_506;
wire   [31:0] grp_fu_272_p2;
reg   [31:0] tmp_6_4_reg_511;
wire   [31:0] tmp2_fu_333_p2;
reg   [31:0] tmp2_reg_541;
wire   [31:0] grp_fu_292_p2;
reg   [31:0] tmp_6_5_reg_551;
wire   [31:0] grp_fu_308_p2;
reg   [31:0] tmp_6_6_reg_556;
wire   [31:0] grp_fu_323_p2;
reg   [31:0] tmp_6_7_reg_561;
wire   [31:0] tmp6_fu_382_p2;
reg   [31:0] tmp6_reg_581;
wire   [31:0] grp_fu_348_p2;
reg   [31:0] tmp_6_8_reg_586;
wire   [0:0] ap_CS_fsm_state15;
wire   [31:0] grp_fu_364_p2;
reg   [31:0] tmp_6_9_reg_591;
wire   [31:0] grp_fu_376_p2;
reg   [31:0] tmp_6_s_reg_596;
wire   [0:0] ap_CS_fsm_state16;
wire   [31:0] tmp3_fu_329_p2;
wire   [31:0] tmp8_fu_394_p2;
wire   [31:0] tmp7_fu_398_p2;
wire   [31:0] tmp5_fu_390_p2;
wire   [31:0] tmp4_fu_403_p2;
wire   [31:0] tmp_fu_386_p2;
reg    grp_fu_348_ce;
wire   [0:0] ap_CS_fsm_state14;
reg    grp_fu_364_ce;
reg    grp_fu_376_ce;
reg   [15:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'b1;
#0 x_preg = 32'b00000000000000000000000000000000;
#0 x_ap_vld_preg = 1'b0;
#0 shift_reg_9 = 32'b00000000000000000000000000000000;
#0 shift_reg_8 = 32'b00000000000000000000000000000000;
#0 shift_reg_7 = 32'b00000000000000000000000000000000;
#0 shift_reg_6 = 32'b00000000000000000000000000000000;
#0 shift_reg_5 = 32'b00000000000000000000000000000000;
#0 shift_reg_4 = 32'b00000000000000000000000000000000;
#0 shift_reg_3 = 32'b00000000000000000000000000000000;
#0 shift_reg_2 = 32'b00000000000000000000000000000000;
#0 shift_reg_1 = 32'b00000000000000000000000000000000;
#0 shift_reg_0 = 32'b00000000000000000000000000000000;
end

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_9),
    .din1(reg_188),
    .ce(1'b1),
    .dout(grp_fu_208_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_8),
    .din1(reg_192),
    .ce(1'b1),
    .dout(grp_fu_224_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_7),
    .din1(reg_196),
    .ce(1'b1),
    .dout(grp_fu_240_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_6),
    .din1(reg_200),
    .ce(1'b1),
    .dout(grp_fu_256_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_5),
    .din1(reg_188),
    .ce(1'b1),
    .dout(grp_fu_272_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_4),
    .din1(reg_192),
    .ce(1'b1),
    .dout(grp_fu_292_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_3),
    .din1(c_load_6_reg_491),
    .ce(1'b1),
    .dout(grp_fu_308_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_2),
    .din1(reg_188),
    .ce(1'b1),
    .dout(grp_fu_323_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_1),
    .din1(reg_196),
    .ce(grp_fu_348_ce),
    .dout(grp_fu_348_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shift_reg_0),
    .din1(reg_200),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p2)
);

fir_mul_32s_32s_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_mul_32s_32s_3bkb_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_188),
    .din1(x_in_sig),
    .ce(grp_fu_376_ce),
    .dout(grp_fu_376_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_ap_vld_preg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            x_ap_vld_preg <= 1'b0;
        end else if (((1'b1 == x_ap_vld) & ~((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)))) begin
            x_ap_vld_preg <= x_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_preg <= ap_const_lv32_0;
    end else begin
        if (((1'b1 == x_ap_vld) & ~((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)))) begin
            x_preg <= x;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        c_load_6_reg_491 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_188 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7))) begin
        reg_192 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_196 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_200 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & ~(x_ap_vld_in_sig == 1'b0))) begin
        shift_reg_0 <= x_in_sig;
        shift_reg_1 <= shift_reg_0;
        shift_reg_2 <= shift_reg_1;
        tmp6_reg_581 <= tmp6_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        shift_reg_3 <= shift_reg_2;
        shift_reg_4 <= shift_reg_3;
        shift_reg_5 <= shift_reg_4;
        tmp2_reg_541 <= tmp2_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        shift_reg_6 <= shift_reg_5;
        shift_reg_7 <= shift_reg_6;
        shift_reg_8 <= shift_reg_7;
        tmp1_reg_486 <= tmp1_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        shift_reg_9 <= shift_reg_8;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_6_1_reg_456 <= grp_fu_224_p2;
        tmp_6_reg_451 <= grp_fu_208_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_6_2_reg_501 <= grp_fu_240_p2;
        tmp_6_3_reg_506 <= grp_fu_256_p2;
        tmp_6_4_reg_511 <= grp_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_6_5_reg_551 <= grp_fu_292_p2;
        tmp_6_6_reg_556 <= grp_fu_308_p2;
        tmp_6_7_reg_561 <= grp_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_6_8_reg_586 <= grp_fu_348_p2;
        tmp_6_9_reg_591 <= grp_fu_364_p2;
        tmp_6_s_reg_596 <= grp_fu_376_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        c_address0 = ap_const_lv64_0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        c_address0 = ap_const_lv64_1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        c_address0 = ap_const_lv64_2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        c_address0 = ap_const_lv64_3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        c_address0 = ap_const_lv64_4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        c_address0 = ap_const_lv64_5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        c_address0 = ap_const_lv64_6;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        c_address0 = ap_const_lv64_7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_address0 = ap_const_lv64_8;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_address0 = ap_const_lv64_9;
    end else if ((ap_CS_fsm_state1 == 1'b1)) begin
        c_address0 = ap_const_lv64_A;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state11) | ((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0)) | (1'b1 == ap_CS_fsm_state8))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & ~(x_ap_vld_in_sig == 1'b0)) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_fu_348_ce = 1'b1;
    end else begin
        grp_fu_348_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & ~(x_ap_vld_in_sig == 1'b0)) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & ~(x_ap_vld_in_sig == 1'b0)) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_fu_376_ce = 1'b1;
    end else begin
        grp_fu_376_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == x_ap_vld)) begin
        x_ap_vld_in_sig = x_ap_vld;
    end else begin
        x_ap_vld_in_sig = x_ap_vld_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        x_blk_n = x_ap_vld;
    end else begin
        x_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == x_ap_vld)) begin
        x_in_sig = x;
    end else begin
        x_in_sig = x_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (~(x_ap_vld_in_sig == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state10 = ap_CS_fsm[ap_const_lv32_9];

assign ap_CS_fsm_state11 = ap_CS_fsm[ap_const_lv32_A];

assign ap_CS_fsm_state12 = ap_CS_fsm[ap_const_lv32_B];

assign ap_CS_fsm_state13 = ap_CS_fsm[ap_const_lv32_C];

assign ap_CS_fsm_state14 = ap_CS_fsm[ap_const_lv32_D];

assign ap_CS_fsm_state15 = ap_CS_fsm[ap_const_lv32_E];

assign ap_CS_fsm_state16 = ap_CS_fsm[ap_const_lv32_F];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state3 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_state5 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_state6 = ap_CS_fsm[ap_const_lv32_5];

assign ap_CS_fsm_state7 = ap_CS_fsm[ap_const_lv32_6];

assign ap_CS_fsm_state8 = ap_CS_fsm[ap_const_lv32_7];

assign ap_CS_fsm_state9 = ap_CS_fsm[ap_const_lv32_8];

assign tmp1_fu_278_p2 = (tmp_6_reg_451 + tmp_6_1_reg_456);

assign tmp2_fu_333_p2 = (tmp3_fu_329_p2 + tmp_6_2_reg_501);

assign tmp3_fu_329_p2 = (tmp_6_3_reg_506 + tmp_6_4_reg_511);

assign tmp4_fu_403_p2 = (tmp7_fu_398_p2 + tmp5_fu_390_p2);

assign tmp5_fu_390_p2 = (tmp6_reg_581 + tmp_6_5_reg_551);

assign tmp6_fu_382_p2 = (tmp_6_6_reg_556 + tmp_6_7_reg_561);

assign tmp7_fu_398_p2 = (tmp8_fu_394_p2 + tmp_6_8_reg_586);

assign tmp8_fu_394_p2 = (tmp_6_9_reg_591 + tmp_6_s_reg_596);

assign tmp_fu_386_p2 = (tmp2_reg_541 + tmp1_reg_486);

assign y = (tmp4_fu_403_p2 + tmp_fu_386_p2);

endmodule //fir
