# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ARM/ARM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM || ORIG_REF_NAME==ARM}]

# IP: bd/ARM/ip/ARM_processing_system7_0_0/ARM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_processing_system7_0_0 || ORIG_REF_NAME==ARM_processing_system7_0_0}]

# IP: bd/ARM/ip/ARM_axi_gpio_0_0_1/ARM_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_axi_gpio_0_0 || ORIG_REF_NAME==ARM_axi_gpio_0_0}]

# IP: bd/ARM/ip/ARM_ps7_0_axi_periph_0_1/ARM_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_ps7_0_axi_periph_0 || ORIG_REF_NAME==ARM_ps7_0_axi_periph_0}]

# IP: bd/ARM/ip/ARM_rst_ps7_0_100M_0_1/ARM_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_rst_ps7_0_100M_0 || ORIG_REF_NAME==ARM_rst_ps7_0_100M_0}]

# IP: bd/ARM/ip/ARM_xbar_0/ARM_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_xbar_0 || ORIG_REF_NAME==ARM_xbar_0}]

# IP: bd/ARM/ip/ARM_axi_gpio_0_2/ARM_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_axi_gpio_0_2 || ORIG_REF_NAME==ARM_axi_gpio_0_2}]

# IP: bd/ARM/ip/ARM_auto_pc_0/ARM_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_auto_pc_0 || ORIG_REF_NAME==ARM_auto_pc_0}]

# XDC: bd/ARM/ARM_ooc.xdc
