# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nikolas/vivado_proj/test/test.cache/wt [current_project]
set_property parent.project_path /home/nikolas/vivado_proj/test/test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/nikolas/vivado_proj/test/test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/nikolas/Git_Repos/CE435/lab1/step7/OneHCounter_Nbits.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/GrayCounter_Nbit_Pulse2.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/GrayCounter_Nbit_Pulse.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/GrayCounter_Nbits.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/debouncer.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/OneCCounter_Nbits.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/BinCounter_Nbits.v
  /home/nikolas/Git_Repos/CE435/lab1/step7/GrayCounter_System.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nikolas/Git_Repos/CE435/lab1/step7/lab1_constraints.xdc
set_property used_in_implementation false [get_files /home/nikolas/Git_Repos/CE435/lab1/step7/lab1_constraints.xdc]


synth_design -top GrayCounter_System -part xc7z020clg484-1


write_checkpoint -force -noxdef GrayCounter_System.dcp

catch { report_utilization -file GrayCounter_System_utilization_synth.rpt -pb GrayCounter_System_utilization_synth.pb }
