// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "XSOBEL_INPUT_BUS"
#define AUTOTB_TVIN_XSOBEL_INPUT_BUS  "../tv/cdatafile/c.sobel.autotvin_XSOBEL_INPUT_BUS.dat"
// wrapc file define: "XSOBEL_OUTPUT_BUS"
#define AUTOTB_TVOUT_XSOBEL_OUTPUT_BUS  "../tv/cdatafile/c.sobel.autotvout_XSOBEL_OUTPUT_BUS.dat"
#define AUTOTB_TVIN_XSOBEL_OUTPUT_BUS  "../tv/cdatafile/c.sobel.autotvin_XSOBEL_OUTPUT_BUS.dat"
// wrapc file define: "input_r"
#define AUTOTB_TVIN_input_r  "../tv/cdatafile/c.sobel.autotvin_input_r.dat"
// wrapc file define: "output_r"
#define AUTOTB_TVIN_output_r  "../tv/cdatafile/c.sobel.autotvin_output_r.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "XSOBEL_OUTPUT_BUS"
#define AUTOTB_TVOUT_PC_XSOBEL_OUTPUT_BUS  "../tv/rtldatafile/rtl.sobel.autotvout_XSOBEL_OUTPUT_BUS.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			XSOBEL_INPUT_BUS_depth = 0;
			XSOBEL_OUTPUT_BUS_depth = 0;
			input_r_depth = 0;
			output_r_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{XSOBEL_INPUT_BUS " << XSOBEL_INPUT_BUS_depth << "}\n";
			total_list << "{XSOBEL_OUTPUT_BUS " << XSOBEL_OUTPUT_BUS_depth << "}\n";
			total_list << "{input_r " << input_r_depth << "}\n";
			total_list << "{output_r " << output_r_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int XSOBEL_INPUT_BUS_depth;
		int XSOBEL_OUTPUT_BUS_depth;
		int input_r_depth;
		int output_r_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void sobel (
char* input,
char* output);

extern "C" void AESL_WRAP_sobel (
char* input,
char* output)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "XSOBEL_OUTPUT_BUS"
		aesl_fh.read(AUTOTB_TVOUT_PC_XSOBEL_OUTPUT_BUS, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_XSOBEL_OUTPUT_BUS, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_XSOBEL_OUTPUT_BUS, AESL_token); // data

			sc_bv<8> *XSOBEL_OUTPUT_BUS_pc_buffer = new sc_bv<8>[1048576];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'XSOBEL_OUTPUT_BUS', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'XSOBEL_OUTPUT_BUS', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					XSOBEL_OUTPUT_BUS_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_XSOBEL_OUTPUT_BUS, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_XSOBEL_OUTPUT_BUS))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: XSOBEL_OUTPUT_BUS
				{
					// bitslice(7, 0)
					// {
						// celement: output(7, 0)
						// {
							sc_lv<8>* output_lv0_0_1048575_1 = new sc_lv<8>[1048576];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output(7, 0)
						{
							// carray: (0) => (1048575) @ (1)
							for (int i_0 = 0; i_0 <= 1048575; i_0 += 1)
							{
								if (&(output[0]) != NULL) // check the null address if the c port is array or others
								{
									output_lv0_0_1048575_1[hls_map_index++].range(7, 0) = sc_bv<8>(XSOBEL_OUTPUT_BUS_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output(7, 0)
						{
							// carray: (0) => (1048575) @ (1)
							for (int i_0 = 0; i_0 <= 1048575; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : output[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : output[0]
								// output_left_conversion : output[i_0]
								// output_type_conversion : (output_lv0_0_1048575_1[hls_map_index++]).to_uint64()
								if (&(output[0]) != NULL) // check the null address if the c port is array or others
								{
									output[i_0] = (output_lv0_0_1048575_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] XSOBEL_OUTPUT_BUS_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "XSOBEL_INPUT_BUS"
		char* tvin_XSOBEL_INPUT_BUS = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_XSOBEL_INPUT_BUS);

		// "XSOBEL_OUTPUT_BUS"
		char* tvin_XSOBEL_OUTPUT_BUS = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_XSOBEL_OUTPUT_BUS);
		char* tvout_XSOBEL_OUTPUT_BUS = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_XSOBEL_OUTPUT_BUS);

		// "input_r"
		char* tvin_input_r = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_input_r);

		// "output_r"
		char* tvin_output_r = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_r);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_XSOBEL_INPUT_BUS, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_XSOBEL_INPUT_BUS, tvin_XSOBEL_INPUT_BUS);

		sc_bv<8>* XSOBEL_INPUT_BUS_tvin_wrapc_buffer = new sc_bv<8>[1048576];

		// RTL Name: XSOBEL_INPUT_BUS
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: input(7, 0)
				{
					// carray: (0) => (1048575) @ (1)
					for (int i_0 = 0; i_0 <= 1048575; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : input[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : input[0]
						// regulate_c_name       : input
						// input_type_conversion : input[i_0]
						if (&(input[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> input_tmp_mem;
							input_tmp_mem = input[i_0];
							XSOBEL_INPUT_BUS_tvin_wrapc_buffer[hls_map_index++].range(7, 0) = input_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1048576; i++)
		{
			sprintf(tvin_XSOBEL_INPUT_BUS, "%s\n", (XSOBEL_INPUT_BUS_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_XSOBEL_INPUT_BUS, tvin_XSOBEL_INPUT_BUS);
		}

		tcl_file.set_num(1048576, &tcl_file.XSOBEL_INPUT_BUS_depth);
		sprintf(tvin_XSOBEL_INPUT_BUS, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_XSOBEL_INPUT_BUS, tvin_XSOBEL_INPUT_BUS);

		// release memory allocation
		delete [] XSOBEL_INPUT_BUS_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_XSOBEL_OUTPUT_BUS, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_XSOBEL_OUTPUT_BUS, tvin_XSOBEL_OUTPUT_BUS);

		sc_bv<8>* XSOBEL_OUTPUT_BUS_tvin_wrapc_buffer = new sc_bv<8>[1048576];

		// RTL Name: XSOBEL_OUTPUT_BUS
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output(7, 0)
				{
					// carray: (0) => (1048575) @ (1)
					for (int i_0 = 0; i_0 <= 1048575; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : output[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : output[0]
						// regulate_c_name       : output
						// input_type_conversion : output[i_0]
						if (&(output[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_tmp_mem;
							output_tmp_mem = output[i_0];
							XSOBEL_OUTPUT_BUS_tvin_wrapc_buffer[hls_map_index++].range(7, 0) = output_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1048576; i++)
		{
			sprintf(tvin_XSOBEL_OUTPUT_BUS, "%s\n", (XSOBEL_OUTPUT_BUS_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_XSOBEL_OUTPUT_BUS, tvin_XSOBEL_OUTPUT_BUS);
		}

		tcl_file.set_num(1048576, &tcl_file.XSOBEL_OUTPUT_BUS_depth);
		sprintf(tvin_XSOBEL_OUTPUT_BUS, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_XSOBEL_OUTPUT_BUS, tvin_XSOBEL_OUTPUT_BUS);

		// release memory allocation
		delete [] XSOBEL_OUTPUT_BUS_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_input_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_input_r, tvin_input_r);

		sc_bv<32> input_r_tvin_wrapc_buffer;

		// RTL Name: input_r
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_input_r, "%s\n", (input_r_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_input_r, tvin_input_r);
		}

		tcl_file.set_num(1, &tcl_file.input_r_depth);
		sprintf(tvin_input_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_input_r, tvin_input_r);

		// [[transaction]]
		sprintf(tvin_output_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_output_r, tvin_output_r);

		sc_bv<32> output_r_tvin_wrapc_buffer;

		// RTL Name: output_r
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_output_r, "%s\n", (output_r_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_output_r, tvin_output_r);
		}

		tcl_file.set_num(1, &tcl_file.output_r_depth);
		sprintf(tvin_output_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_output_r, tvin_output_r);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		sobel(input, output);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_XSOBEL_OUTPUT_BUS, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_XSOBEL_OUTPUT_BUS, tvout_XSOBEL_OUTPUT_BUS);

		sc_bv<8>* XSOBEL_OUTPUT_BUS_tvout_wrapc_buffer = new sc_bv<8>[1048576];

		// RTL Name: XSOBEL_OUTPUT_BUS
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output(7, 0)
				{
					// carray: (0) => (1048575) @ (1)
					for (int i_0 = 0; i_0 <= 1048575; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : output[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : output[0]
						// regulate_c_name       : output
						// input_type_conversion : output[i_0]
						if (&(output[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_tmp_mem;
							output_tmp_mem = output[i_0];
							XSOBEL_OUTPUT_BUS_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1048576; i++)
		{
			sprintf(tvout_XSOBEL_OUTPUT_BUS, "%s\n", (XSOBEL_OUTPUT_BUS_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_XSOBEL_OUTPUT_BUS, tvout_XSOBEL_OUTPUT_BUS);
		}

		tcl_file.set_num(1048576, &tcl_file.XSOBEL_OUTPUT_BUS_depth);
		sprintf(tvout_XSOBEL_OUTPUT_BUS, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_XSOBEL_OUTPUT_BUS, tvout_XSOBEL_OUTPUT_BUS);

		// release memory allocation
		delete [] XSOBEL_OUTPUT_BUS_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "XSOBEL_INPUT_BUS"
		delete [] tvin_XSOBEL_INPUT_BUS;
		// release memory allocation: "XSOBEL_OUTPUT_BUS"
		delete [] tvout_XSOBEL_OUTPUT_BUS;
		delete [] tvin_XSOBEL_OUTPUT_BUS;
		// release memory allocation: "input_r"
		delete [] tvin_input_r;
		// release memory allocation: "output_r"
		delete [] tvin_output_r;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

