# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /run/media/nikolas/Linux_Data/CE435_vidado_labs/Lab_4/project/lab4/lab4.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xci
# IP: The module: 'block_diagram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/nikolas/Linux_Data/CE435_vidado_labs/Lab_4/project/lab4/lab4.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /run/media/nikolas/Linux_Data/CE435_vidado_labs/Lab_4/project/lab4/lab4.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xci
# IP: The module: 'block_diagram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/nikolas/Linux_Data/CE435_vidado_labs/Lab_4/project/lab4/lab4.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_diagram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
