#pragma line 1 "sobel_opt.c" ::: -10
#pragma line 1 "sobel_opt.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "sobel_opt.c" 2 ::: 184
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 213
#pragma line 122 "/usr/include/features.h" 3 4 ::: 310
#pragma line 177 "/usr/include/features.h" 3 4 ::: 343
#pragma line 188 "/usr/include/features.h" 3 4 ::: 346
#pragma line 341 "/usr/include/features.h" 3 4 ::: 377
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 381
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 416
#pragma line 344 "/usr/include/features.h" 2 3 4 ::: 427
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 450
#pragma line 49 "/usr/include/sys/cdefs.h" 3 4 ::: 491
#pragma line 80 "/usr/include/sys/cdefs.h" 3 4 ::: 497
#pragma line 106 "/usr/include/sys/cdefs.h" 3 4 ::: 515
#pragma line 119 "/usr/include/sys/cdefs.h" 3 4 ::: 521
#pragma line 131 "/usr/include/sys/cdefs.h" 3 4 ::: 525
#pragma line 147 "/usr/include/sys/cdefs.h" 3 4 ::: 527
#pragma line 165 "/usr/include/sys/cdefs.h" 3 4 ::: 531
#pragma line 192 "/usr/include/sys/cdefs.h" 3 4 ::: 541
#pragma line 252 "/usr/include/sys/cdefs.h" 3 4 ::: 594
#pragma line 305 "/usr/include/sys/cdefs.h" 3 4 ::: 635
#pragma line 346 "/usr/include/sys/cdefs.h" 3 4 ::: 660
#pragma line 410 "/usr/include/sys/cdefs.h" 3 4 ::: 684
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 685
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 687
#pragma line 411 "/usr/include/sys/cdefs.h" 2 3 4 ::: 689
#pragma line 366 "/usr/include/features.h" 2 3 4 ::: 690
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 715
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 726
#pragma line 11 "/usr/include/gnu/stubs.h" 2 3 4 ::: 731
#pragma line 390 "/usr/include/features.h" 2 3 4 ::: 732
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 733
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 739
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 780
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 783
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 785
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 813
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 815
#pragma line 28 "/usr/include/bits/types.h" 2 3 4 ::: 817
#pragma line 116 "/usr/include/bits/types.h" 3 4 ::: 878
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 885
#pragma line 26 "/usr/include/bits/typesizes.h" 3 4 ::: 903
#pragma line 76 "/usr/include/bits/typesizes.h" 3 4 ::: 908
#pragma line 122 "/usr/include/bits/types.h" 2 3 4 ::: 919
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 988
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1002
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1005
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1006
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1038
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1054
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1079
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1082
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1087
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1109
#pragma line 899 "/usr/include/wchar.h" 3 4 ::: 1130
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1133
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1144
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1154
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1156
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1160
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1209
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1210
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1218
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1242
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1253
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1294
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1296
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1318
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1344
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1348
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1363
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1375
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1381
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1383
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1393
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1415
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 1431
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1448
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1480
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1526
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1540
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1543
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1619
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1658
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1699
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1812
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1875
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1924
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1935
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 1965
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1993
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2025
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2037
#pragma line 2 "sobel_opt.c" 2 ::: 2040
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2041
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2062
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2067
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2092
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2095
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2132
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2135
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2172
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2215
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2237
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2239
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2244
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2247
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2257
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2262
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2283
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2314
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2337
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2343
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2367
#pragma line 3 "sobel_opt.c" 2 ::: 2393
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2394
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2427
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2452
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2455
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 2465
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2494
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 2495
#pragma line 64 "/usr/include/bits/waitstatus.h" 3 4 ::: 2551
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2552
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 2589
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2591
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2595
#pragma line 1 "/usr/include/bits/byteswap.h" 1 3 4 ::: 2598
#pragma line 28 "/usr/include/bits/byteswap.h" 3 4 ::: 2616
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2617
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 2619
#pragma line 29 "/usr/include/bits/byteswap.h" 2 3 4 ::: 2621
#pragma line 1 "/usr/include/bits/byteswap-16.h" 1 3 4 ::: 2629
#pragma line 36 "/usr/include/bits/byteswap.h" 2 3 4 ::: 2647
#pragma line 56 "/usr/include/bits/byteswap.h" 3 4 ::: 2650
#pragma line 96 "/usr/include/bits/byteswap.h" 3 4 ::: 2653
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2655
#pragma line 65 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 2656
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2690
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2696
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2712
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2714
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2836
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 2850
#pragma line 33 "/usr/include/sys/types.h" 3 4 ::: 2871
#pragma line 60 "/usr/include/sys/types.h" 3 4 ::: 2888
#pragma line 98 "/usr/include/sys/types.h" 3 4 ::: 2910
#pragma line 115 "/usr/include/sys/types.h" 3 4 ::: 2918
#pragma line 132 "/usr/include/sys/types.h" 3 4 ::: 2927
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2928
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2949
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2952
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2955
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2958
#pragma line 133 "/usr/include/sys/types.h" 2 3 4 ::: 2961
#pragma line 146 "/usr/include/sys/types.h" 3 4 ::: 2962
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2963
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2988
#pragma line 147 "/usr/include/sys/types.h" 2 3 4 ::: 2991
#pragma line 186 "/usr/include/sys/types.h" 3 4 ::: 3001
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3036
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3067
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3090
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 3092
#pragma line 23 "/usr/include/bits/select.h" 2 3 4 ::: 3094
#pragma line 31 "/usr/include/sys/select.h" 2 3 4 ::: 3095
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3099
#pragma line 34 "/usr/include/sys/select.h" 2 3 4 ::: 3139
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3150
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3171
#pragma line 44 "/usr/include/sys/select.h" 2 3 4 ::: 3179
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3181
#pragma line 46 "/usr/include/sys/select.h" 2 3 4 ::: 3216
#pragma line 98 "/usr/include/sys/select.h" 3 4 ::: 3261
#pragma line 220 "/usr/include/sys/types.h" 2 3 4 ::: 3291
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3295
#pragma line 26 "/usr/include/sys/sysmacros.h" 3 4 ::: 3313
#pragma line 60 "/usr/include/sys/sysmacros.h" 3 4 ::: 3324
#pragma line 223 "/usr/include/sys/types.h" 2 3 4 ::: 3326
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 3348
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 3352
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3374
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 3376
#pragma line 22 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 3378
#pragma line 58 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3379
#pragma line 88 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3402
#pragma line 125 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3424
#pragma line 220 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3501
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 3532
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3533
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3676
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3705
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3730
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3755
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3758
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3767
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3780
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3787
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3799
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3810
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3856
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3865
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3872
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3878
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3893
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 4044
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 4046
#pragma line 1 "/usr/include/bits/stdlib-float.h" 1 3 4 ::: 4055
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4073
#pragma line 4 "sobel_opt.c" 2 ::: 4076
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4077
#pragma line 30 "/usr/include/math.h" 3 4 ::: 4099
#pragma line 1 "/usr/include/bits/math-vector.h" 1 3 4 ::: 4102
#pragma line 1 "/usr/include/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4128
#pragma line 26 "/usr/include/bits/math-vector.h" 2 3 4 ::: 4160
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 4161
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 4166
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 4191
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 4193
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 4218
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 4219
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 4238
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 4242
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 4266
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 4270
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 4295
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 4300
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 4317
#pragma line 41 "/usr/include/bits/mathdef.h" 3 4 ::: 4323
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4330
#pragma line 82 "/usr/include/math.h" 3 4 ::: 4336
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 4337
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 4414
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 4444
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 4683
#pragma line 83 "/usr/include/math.h" 2 3 4 ::: 4686
#pragma line 101 "/usr/include/math.h" 3 4 ::: 4697
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 4698
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 4775
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 4805
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 5044
#pragma line 102 "/usr/include/math.h" 2 3 4 ::: 5047
#pragma line 135 "/usr/include/math.h" 3 4 ::: 5048
#pragma line 146 "/usr/include/math.h" 3 4 ::: 5051
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 5052
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 5129
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 5159
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 5398
#pragma line 147 "/usr/include/math.h" 2 3 4 ::: 5401
#pragma line 161 "/usr/include/math.h" 3 4 ::: 5402
#pragma line 234 "/usr/include/math.h" 3 4 ::: 5465
#pragma line 246 "/usr/include/math.h" 3 4 ::: 5467
#pragma line 258 "/usr/include/math.h" 3 4 ::: 5469
#pragma line 274 "/usr/include/math.h" 3 4 ::: 5475
#pragma line 286 "/usr/include/math.h" 3 4 ::: 5477
#pragma line 314 "/usr/include/math.h" 3 4 ::: 5485
#pragma line 379 "/usr/include/math.h" 3 4 ::: 5539
#pragma line 396 "/usr/include/math.h" 3 4 ::: 5541
#pragma line 416 "/usr/include/math.h" 3 4 ::: 5545
#pragma line 438 "/usr/include/math.h" 3 4 ::: 5560
#pragma line 5 "sobel_opt.c" 2 ::: 5616
#pragma line 1 "./sobel_opt.h" 1 ::: 5619
#pragma line 7 "sobel_opt.c" 2 ::: 5627
