#pragma line 1 "sobel_opt.c" ::: 0
#pragma line 1 "sobel_opt.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "sobel_opt.c" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 223
#pragma line 122 "/usr/include/features.h" 3 4 ::: 320
#pragma line 177 "/usr/include/features.h" 3 4 ::: 353
#pragma line 188 "/usr/include/features.h" 3 4 ::: 356
#pragma line 341 "/usr/include/features.h" 3 4 ::: 387
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 391
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 426
#pragma line 344 "/usr/include/features.h" 2 3 4 ::: 437
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 460
#pragma line 49 "/usr/include/sys/cdefs.h" 3 4 ::: 501
#pragma line 80 "/usr/include/sys/cdefs.h" 3 4 ::: 507
#pragma line 106 "/usr/include/sys/cdefs.h" 3 4 ::: 525
#pragma line 119 "/usr/include/sys/cdefs.h" 3 4 ::: 531
#pragma line 131 "/usr/include/sys/cdefs.h" 3 4 ::: 535
#pragma line 147 "/usr/include/sys/cdefs.h" 3 4 ::: 537
#pragma line 165 "/usr/include/sys/cdefs.h" 3 4 ::: 541
#pragma line 192 "/usr/include/sys/cdefs.h" 3 4 ::: 551
#pragma line 252 "/usr/include/sys/cdefs.h" 3 4 ::: 604
#pragma line 305 "/usr/include/sys/cdefs.h" 3 4 ::: 645
#pragma line 346 "/usr/include/sys/cdefs.h" 3 4 ::: 670
#pragma line 410 "/usr/include/sys/cdefs.h" 3 4 ::: 694
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 695
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 697
#pragma line 411 "/usr/include/sys/cdefs.h" 2 3 4 ::: 699
#pragma line 366 "/usr/include/features.h" 2 3 4 ::: 700
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 725
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 736
#pragma line 11 "/usr/include/gnu/stubs.h" 2 3 4 ::: 741
#pragma line 390 "/usr/include/features.h" 2 3 4 ::: 742
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 743
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 749
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 790
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 793
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 795
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 823
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 825
#pragma line 28 "/usr/include/bits/types.h" 2 3 4 ::: 827
#pragma line 116 "/usr/include/bits/types.h" 3 4 ::: 888
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 895
#pragma line 26 "/usr/include/bits/typesizes.h" 3 4 ::: 913
#pragma line 76 "/usr/include/bits/typesizes.h" 3 4 ::: 918
#pragma line 122 "/usr/include/bits/types.h" 2 3 4 ::: 929
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 998
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1012
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1015
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1016
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1048
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1064
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1089
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1092
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1097
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1119
#pragma line 899 "/usr/include/wchar.h" 3 4 ::: 1140
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1143
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1154
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1164
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1166
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1170
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1219
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1220
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1226
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1228
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1252
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1263
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1304
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1306
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1328
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1354
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1358
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1373
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1385
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1391
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1393
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1403
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1425
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 1441
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1458
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1490
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1536
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1550
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1553
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1629
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1668
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1709
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1822
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1885
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1934
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1945
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 1975
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2003
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2035
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2047
#pragma line 2 "sobel_opt.c" 2 ::: 2050
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2051
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2072
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2077
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2102
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2105
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2142
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2145
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2182
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2225
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2247
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2249
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2254
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2257
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2267
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2272
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2293
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2324
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2347
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2353
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2377
#pragma line 3 "sobel_opt.c" 2 ::: 2403
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2404
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2437
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2462
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2465
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 2475
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2504
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 2505
#pragma line 64 "/usr/include/bits/waitstatus.h" 3 4 ::: 2561
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2562
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 2599
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2601
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2605
#pragma line 1 "/usr/include/bits/byteswap.h" 1 3 4 ::: 2608
#pragma line 28 "/usr/include/bits/byteswap.h" 3 4 ::: 2626
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2627
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 2629
#pragma line 29 "/usr/include/bits/byteswap.h" 2 3 4 ::: 2631
#pragma line 1 "/usr/include/bits/byteswap-16.h" 1 3 4 ::: 2639
#pragma line 36 "/usr/include/bits/byteswap.h" 2 3 4 ::: 2657
#pragma line 56 "/usr/include/bits/byteswap.h" 3 4 ::: 2660
#pragma line 96 "/usr/include/bits/byteswap.h" 3 4 ::: 2663
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2665
#pragma line 65 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 2666
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2700
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2706
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2722
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2724
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2846
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 2860
#pragma line 33 "/usr/include/sys/types.h" 3 4 ::: 2881
#pragma line 60 "/usr/include/sys/types.h" 3 4 ::: 2898
#pragma line 98 "/usr/include/sys/types.h" 3 4 ::: 2920
#pragma line 115 "/usr/include/sys/types.h" 3 4 ::: 2928
#pragma line 132 "/usr/include/sys/types.h" 3 4 ::: 2937
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2938
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2959
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2962
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2965
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2968
#pragma line 133 "/usr/include/sys/types.h" 2 3 4 ::: 2971
#pragma line 146 "/usr/include/sys/types.h" 3 4 ::: 2972
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2973
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2998
#pragma line 147 "/usr/include/sys/types.h" 2 3 4 ::: 3001
#pragma line 186 "/usr/include/sys/types.h" 3 4 ::: 3011
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3046
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3077
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3100
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 3102
#pragma line 23 "/usr/include/bits/select.h" 2 3 4 ::: 3104
#pragma line 31 "/usr/include/sys/select.h" 2 3 4 ::: 3105
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3109
#pragma line 34 "/usr/include/sys/select.h" 2 3 4 ::: 3149
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3160
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3181
#pragma line 44 "/usr/include/sys/select.h" 2 3 4 ::: 3189
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3191
#pragma line 46 "/usr/include/sys/select.h" 2 3 4 ::: 3226
#pragma line 98 "/usr/include/sys/select.h" 3 4 ::: 3271
#pragma line 220 "/usr/include/sys/types.h" 2 3 4 ::: 3301
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3305
#pragma line 26 "/usr/include/sys/sysmacros.h" 3 4 ::: 3323
#pragma line 60 "/usr/include/sys/sysmacros.h" 3 4 ::: 3334
#pragma line 223 "/usr/include/sys/types.h" 2 3 4 ::: 3336
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 3358
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 3362
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3384
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 3386
#pragma line 22 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 3388
#pragma line 58 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3389
#pragma line 88 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3412
#pragma line 125 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3434
#pragma line 220 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3511
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 3542
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3543
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3686
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3715
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3740
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3765
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3768
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3777
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3790
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3797
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3809
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3820
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3866
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3875
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3882
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3888
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3903
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 4054
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 4056
#pragma line 1 "/usr/include/bits/stdlib-float.h" 1 3 4 ::: 4065
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4083
#pragma line 4 "sobel_opt.c" 2 ::: 4086
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4087
#pragma line 30 "/usr/include/math.h" 3 4 ::: 4109
#pragma line 1 "/usr/include/bits/math-vector.h" 1 3 4 ::: 4112
#pragma line 1 "/usr/include/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4138
#pragma line 26 "/usr/include/bits/math-vector.h" 2 3 4 ::: 4170
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 4171
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 4176
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 4201
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 4203
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 4228
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 4229
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 4248
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 4252
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 4276
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 4280
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 4305
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 4310
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 4327
#pragma line 41 "/usr/include/bits/mathdef.h" 3 4 ::: 4333
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4340
#pragma line 82 "/usr/include/math.h" 3 4 ::: 4346
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 4347
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 4424
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 4454
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 4693
#pragma line 83 "/usr/include/math.h" 2 3 4 ::: 4696
#pragma line 101 "/usr/include/math.h" 3 4 ::: 4707
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 4708
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 4785
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 4815
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 5054
#pragma line 102 "/usr/include/math.h" 2 3 4 ::: 5057
#pragma line 135 "/usr/include/math.h" 3 4 ::: 5058
#pragma line 146 "/usr/include/math.h" 3 4 ::: 5061
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 5062
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 5139
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 5169
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 5408
#pragma line 147 "/usr/include/math.h" 2 3 4 ::: 5411
#pragma line 161 "/usr/include/math.h" 3 4 ::: 5412
#pragma line 234 "/usr/include/math.h" 3 4 ::: 5475
#pragma line 246 "/usr/include/math.h" 3 4 ::: 5477
#pragma line 258 "/usr/include/math.h" 3 4 ::: 5479
#pragma line 274 "/usr/include/math.h" 3 4 ::: 5485
#pragma line 286 "/usr/include/math.h" 3 4 ::: 5487
#pragma line 314 "/usr/include/math.h" 3 4 ::: 5495
#pragma line 379 "/usr/include/math.h" 3 4 ::: 5549
#pragma line 396 "/usr/include/math.h" 3 4 ::: 5551
#pragma line 416 "/usr/include/math.h" 3 4 ::: 5555
#pragma line 438 "/usr/include/math.h" 3 4 ::: 5570
#pragma line 5 "sobel_opt.c" 2 ::: 5626
#pragma line 1 "./sobel_opt.h" 1 ::: 5629
#pragma line 7 "sobel_opt.c" 2 ::: 5637
