set_property PACKAGE_PIN U10 [get_ports DC]
set_property PACKAGE_PIN U9 [get_ports RES]
set_property PACKAGE_PIN AB12 [get_ports SCLK]
set_property PACKAGE_PIN AA12 [get_ports SDIN]
set_property PACKAGE_PIN U11 [get_ports VBAT]
set_property PACKAGE_PIN U12 [get_ports VDD]
set_property IOSTANDARD LVCMOS33 [get_ports DC]
set_property IOSTANDARD LVCMOS33 [get_ports RES]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDIN]
set_property IOSTANDARD LVCMOS33 [get_ports VBAT]
set_property IOSTANDARD LVCMOS33 [get_ports VDD]



#set_property PACKAGE_PIN T22 [get_ports {LED[0]}]
#set_property PACKAGE_PIN T21 [get_ports {LED[1]}]
#set_property PACKAGE_PIN U22 [get_ports {LED[2]}]
#set_property PACKAGE_PIN U21 [get_ports {LED[3]}]
#set_property PACKAGE_PIN V22 [get_ports {LED[4]}]
#set_property PACKAGE_PIN W22 [get_ports {LED[5]}]
#set_property PACKAGE_PIN U19 [get_ports {LED[6]}]
#set_property PACKAGE_PIN U14 [get_ports {LED[7]}]


#set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]