# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /run/media/nikolas/Linux_Data/Git_Repos/CE435/lab2/lab2_interrupt_arm/lab2_interrupt_arm.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_processing_system7_0_0/lab2_simple_arm_processing_system7_0_0.xci
# IP: The module: 'lab2_simple_arm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/nikolas/Linux_Data/Git_Repos/CE435/lab2/lab2_interrupt_arm/lab2_interrupt_arm.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_processing_system7_0_0/lab2_simple_arm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /run/media/nikolas/Linux_Data/Git_Repos/CE435/lab2/lab2_interrupt_arm/lab2_interrupt_arm.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_processing_system7_0_0/lab2_simple_arm_processing_system7_0_0.xci
# IP: The module: 'lab2_simple_arm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/nikolas/Linux_Data/Git_Repos/CE435/lab2/lab2_interrupt_arm/lab2_interrupt_arm.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_processing_system7_0_0/lab2_simple_arm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
