# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/lab2_simple_arm_system_ila_0.xci
# IP: The module: 'lab2_simple_arm_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/bd_4eb0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0 || ORIG_REF_NAME==bd_4eb0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_0/bd_4eb0_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_ila_lib_0 || ORIG_REF_NAME==bd_4eb0_ila_lib_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_1/bd_4eb0_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_g_inst_0 || ORIG_REF_NAME==bd_4eb0_g_inst_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_2/bd_4eb0_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_aw_0 || ORIG_REF_NAME==bd_4eb0_slot_0_aw_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_3/bd_4eb0_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_w_0 || ORIG_REF_NAME==bd_4eb0_slot_0_w_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_4/bd_4eb0_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_b_0 || ORIG_REF_NAME==bd_4eb0_slot_0_b_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_5/bd_4eb0_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_ar_0 || ORIG_REF_NAME==bd_4eb0_slot_0_ar_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_6/bd_4eb0_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_r_0 || ORIG_REF_NAME==bd_4eb0_slot_0_r_0}]

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4eb0_ila_lib_0 || ORIG_REF_NAME==bd_4eb0_ila_lib_0}] {/inst }]/inst ]]

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_0/bd_4eb0_ila_lib_0_ooc.xdc

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_1/bd_4eb0_g_inst_0_ooc.xdc

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/bd_4eb0_ooc.xdc

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/lab2_simple_arm_system_ila_0.xci
# IP: The module: 'lab2_simple_arm_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/bd_4eb0.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0 || ORIG_REF_NAME==bd_4eb0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_0/bd_4eb0_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_ila_lib_0 || ORIG_REF_NAME==bd_4eb0_ila_lib_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_1/bd_4eb0_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_g_inst_0 || ORIG_REF_NAME==bd_4eb0_g_inst_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_2/bd_4eb0_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_aw_0 || ORIG_REF_NAME==bd_4eb0_slot_0_aw_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_3/bd_4eb0_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_w_0 || ORIG_REF_NAME==bd_4eb0_slot_0_w_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_4/bd_4eb0_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_b_0 || ORIG_REF_NAME==bd_4eb0_slot_0_b_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_5/bd_4eb0_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_ar_0 || ORIG_REF_NAME==bd_4eb0_slot_0_ar_0}]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_6/bd_4eb0_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4eb0_slot_0_r_0 || ORIG_REF_NAME==bd_4eb0_slot_0_r_0}]

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4eb0_ila_lib_0 || ORIG_REF_NAME==bd_4eb0_ila_lib_0}] {/inst }]/inst ]]

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_0/bd_4eb0_ila_lib_0_ooc.xdc

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/ip/ip_1/bd_4eb0_g_inst_0_ooc.xdc

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_HwDebug/lab3_HwDebug.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_system_ila_0/bd_0/bd_4eb0_ooc.xdc
