# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_customIP/lab3_customIP.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0.xci
# IP: The module: 'lab2_simple_arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_customIP/lab3_customIP.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/nikolas/Git_Repos/CE435/lab3/lab3_customIP/lab3_customIP.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0.xci
# IP: The module: 'lab2_simple_arm_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nikolas/Git_Repos/CE435/lab3/lab3_customIP/lab3_customIP.srcs/sources_1/bd/lab2_simple_arm/ip/lab2_simple_arm_xbar_0/lab2_simple_arm_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_simple_arm_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
