webtalk_init -webtalk_dir /home/nikolas/Git_Repos/CE435/lab5/Sobel_SW/Lab_5_SW/Lab_5_SW.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-05-29 21:02:10" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "malbf134d93pjv3m9q3m44u1i6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_47" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "47" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2187.468 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1496072388000" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key hwid -value "1495191936000" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key bspid -value "1495196774000" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1496072388000"
webtalk_add_data -client sdk -key uid -value "1496072719000" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key hwid -value "1495191936000" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key bspid -value "1495196774000" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key projSize -value "790.34375" -context "sdk\\\\application/1496072719000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key DebugCount -value "60" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key PerfCount -value "2" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1496080930052"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1496080930052"
webtalk_transmit -clientid 435473939 -regid "" -xml /home/nikolas/Git_Repos/CE435/lab5/Sobel_SW/Lab_5_SW/Lab_5_SW.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/nikolas/Git_Repos/CE435/lab5/Sobel_SW/Lab_5_SW/Lab_5_SW.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/nikolas/Git_Repos/CE435/lab5/Sobel_SW/Lab_5_SW/Lab_5_SW.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
