#pragma line 1 "sobel/sobel_opt.c" ::: 0
#pragma line 1 "sobel/sobel_opt.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "sobel/sobel_opt.c" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 223
#pragma line 122 "/usr/include/features.h" 3 4 ::: 320
#pragma line 156 "/usr/include/features.h" 3 4 ::: 345
#pragma line 180 "/usr/include/features.h" 3 4 ::: 347
#pragma line 191 "/usr/include/features.h" 3 4 ::: 350
#pragma line 343 "/usr/include/features.h" 3 4 ::: 381
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 385
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 420
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 427
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 450
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 491
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 497
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 515
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 594
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 635
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 660
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 684
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 685
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 687
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 689
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 690
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 715
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 726
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 731
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 732
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 733
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 739
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 780
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 783
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 785
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 813
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 815
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 817
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 878
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 885
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 903
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 908
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 919
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 988
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1002
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1005
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1006
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1038
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1054
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1079
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1082
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1087
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1109
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1130
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1133
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1144
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1154
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1156
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1160
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1209
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1210
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1218
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1238
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1249
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1290
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1320
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1346
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1350
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1365
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1377
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1383
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1385
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1395
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1417
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1433
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1450
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1482
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1528
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1542
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1545
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1621
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1660
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1701
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1814
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1877
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1926
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1937
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1967
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1995
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2027
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2039
#pragma line 2 "sobel/sobel_opt.c" 2 ::: 2042
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2043
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2064
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2069
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2094
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2097
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2134
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2137
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2174
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2217
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2239
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2241
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2246
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2249
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2259
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2264
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2285
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2316
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2339
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2345
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2369
#pragma line 3 "sobel/sobel_opt.c" 2 ::: 2395
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2396
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2429
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2454
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2457
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2467
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2496
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2514
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2515
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2571
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2572
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2609
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2611
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2615
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2618
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2636
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2637
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2639
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2641
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2649
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2667
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2670
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2673
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2675
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2676
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2710
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2716
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2732
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2734
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2856
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2870
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2891
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2908
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2930
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2938
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2947
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2948
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2969
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2972
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2975
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2978
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2981
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2982
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2983
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3008
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3011
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3021
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3056
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3087
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3110
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3112
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3114
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3115
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3119
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3159
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3170
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3191
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3199
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3201
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3236
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3281
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3311
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3315
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3333
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3344
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3346
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3368
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3372
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3394
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3396
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3398
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3399
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3422
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3444
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3521
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3552
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3553
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3696
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3725
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3750
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3775
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3778
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3787
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3800
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3807
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3819
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3830
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3876
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3885
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3892
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3898
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3913
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 4064
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 4066
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4075
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4093
#pragma line 4 "sobel/sobel_opt.c" 2 ::: 4096
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4097
#pragma line 30 "/usr/include/math.h" 3 4 ::: 4119
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 4122
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4148
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 4180
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 4181
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 4186
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 4211
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 4213
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 4238
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 4239
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 4258
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 4262
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 4286
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 4290
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 4315
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 4320
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4337
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4343
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4350
#pragma line 83 "/usr/include/math.h" 3 4 ::: 4356
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4357
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4434
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4464
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4705
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 4708
#pragma line 93 "/usr/include/math.h" 3 4 ::: 4709
#pragma line 104 "/usr/include/math.h" 3 4 ::: 4712
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4713
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4790
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4820
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5061
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 5064
#pragma line 139 "/usr/include/math.h" 3 4 ::: 5065
#pragma line 151 "/usr/include/math.h" 3 4 ::: 5068
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5069
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5146
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5176
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5417
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 5420
#pragma line 167 "/usr/include/math.h" 3 4 ::: 5421
#pragma line 248 "/usr/include/math.h" 3 4 ::: 5488
#pragma line 268 "/usr/include/math.h" 3 4 ::: 5490
#pragma line 282 "/usr/include/math.h" 3 4 ::: 5492
#pragma line 304 "/usr/include/math.h" 3 4 ::: 5502
#pragma line 318 "/usr/include/math.h" 3 4 ::: 5504
#pragma line 346 "/usr/include/math.h" 3 4 ::: 5512
#pragma line 411 "/usr/include/math.h" 3 4 ::: 5566
#pragma line 428 "/usr/include/math.h" 3 4 ::: 5568
#pragma line 448 "/usr/include/math.h" 3 4 ::: 5572
#pragma line 470 "/usr/include/math.h" 3 4 ::: 5587
#pragma line 5 "sobel/sobel_opt.c" 2 ::: 5643
#pragma line 1 "sobel/sobel_opt.h" 1 ::: 5644
#pragma line 6 "sobel/sobel_opt.c" 2 ::: 5652
