#pragma line 1 "sobel/sobel_opt.c" ::: -10
#pragma line 1 "sobel/sobel_opt.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "sobel/sobel_opt.c" 2 ::: 184
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 213
#pragma line 122 "/usr/include/features.h" 3 4 ::: 310
#pragma line 156 "/usr/include/features.h" 3 4 ::: 335
#pragma line 180 "/usr/include/features.h" 3 4 ::: 337
#pragma line 191 "/usr/include/features.h" 3 4 ::: 340
#pragma line 343 "/usr/include/features.h" 3 4 ::: 371
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 375
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 410
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 417
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 440
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 481
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 487
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 505
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 511
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 515
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 584
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 625
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 650
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 674
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 675
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 677
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 679
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 680
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 705
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 716
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 721
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 722
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 723
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 729
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 770
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 773
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 775
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 803
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 805
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 807
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 868
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 875
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 893
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 898
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 909
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 978
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 992
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 995
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 996
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1028
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1044
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1069
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1072
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1077
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1099
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1120
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1123
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1134
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1144
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1146
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1150
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1199
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1200
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1206
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1208
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1228
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1239
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1280
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1310
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1336
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1340
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1355
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1367
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1373
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1375
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1385
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1407
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1423
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1440
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1472
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1518
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1532
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1535
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1611
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1650
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1691
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1804
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1867
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1916
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1927
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1957
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1985
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2017
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2029
#pragma line 2 "sobel/sobel_opt.c" 2 ::: 2032
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2033
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2054
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2059
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2084
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2087
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2124
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2127
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2164
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2207
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2229
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2231
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2236
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2239
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2249
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2254
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2275
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2306
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2329
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2335
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2359
#pragma line 3 "sobel/sobel_opt.c" 2 ::: 2385
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2386
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2419
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2444
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2447
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2457
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2486
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2504
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2505
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2561
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2562
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2599
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2601
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2605
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2608
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2626
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2627
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2629
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2631
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2639
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2657
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2660
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2663
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2665
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2666
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2700
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2706
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2722
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2724
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2846
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2860
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2881
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2898
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2920
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2928
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2937
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2938
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2959
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2962
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2965
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2968
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2971
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2972
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2973
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2998
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3001
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3011
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3046
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3077
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3100
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3102
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3104
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3105
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3109
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3149
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3160
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3181
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3189
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3191
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3226
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3271
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3301
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3305
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3323
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3334
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3336
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3358
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3362
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3384
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3386
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3388
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3389
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3412
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3434
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3511
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3542
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3543
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3686
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3715
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3740
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3765
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3768
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3777
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3790
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3797
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3809
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3820
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3866
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3875
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3882
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3888
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3903
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 4054
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 4056
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4065
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4083
#pragma line 4 "sobel/sobel_opt.c" 2 ::: 4086
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4087
#pragma line 30 "/usr/include/math.h" 3 4 ::: 4109
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 4112
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4138
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 4170
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 4171
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 4176
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 4201
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 4203
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 4228
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 4229
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 4248
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 4252
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 4276
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 4280
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 4305
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 4310
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4327
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4333
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4340
#pragma line 83 "/usr/include/math.h" 3 4 ::: 4346
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4347
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4424
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4454
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4695
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 4698
#pragma line 93 "/usr/include/math.h" 3 4 ::: 4699
#pragma line 104 "/usr/include/math.h" 3 4 ::: 4702
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4703
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4780
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4810
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5051
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 5054
#pragma line 139 "/usr/include/math.h" 3 4 ::: 5055
#pragma line 151 "/usr/include/math.h" 3 4 ::: 5058
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5059
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5136
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5166
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5407
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 5410
#pragma line 167 "/usr/include/math.h" 3 4 ::: 5411
#pragma line 248 "/usr/include/math.h" 3 4 ::: 5478
#pragma line 268 "/usr/include/math.h" 3 4 ::: 5480
#pragma line 282 "/usr/include/math.h" 3 4 ::: 5482
#pragma line 304 "/usr/include/math.h" 3 4 ::: 5492
#pragma line 318 "/usr/include/math.h" 3 4 ::: 5494
#pragma line 346 "/usr/include/math.h" 3 4 ::: 5502
#pragma line 411 "/usr/include/math.h" 3 4 ::: 5556
#pragma line 428 "/usr/include/math.h" 3 4 ::: 5558
#pragma line 448 "/usr/include/math.h" 3 4 ::: 5562
#pragma line 470 "/usr/include/math.h" 3 4 ::: 5577
#pragma line 5 "sobel/sobel_opt.c" 2 ::: 5633
#pragma line 1 "sobel/sobel_opt.h" 1 ::: 5634
#pragma line 6 "sobel/sobel_opt.c" 2 ::: 5642
