# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/block_diagram/block_diagram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram || ORIG_REF_NAME==block_diagram}]

# IP: bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_processing_system7_0_0 || ORIG_REF_NAME==block_diagram_processing_system7_0_0}]

# IP: bd/block_diagram/ip/block_diagram_axi_gpio_0_0/block_diagram_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_axi_gpio_0_0 || ORIG_REF_NAME==block_diagram_axi_gpio_0_0}]

# IP: bd/block_diagram/ip/block_diagram_ps7_0_axi_periph_0/block_diagram_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==block_diagram_ps7_0_axi_periph_0}]

# IP: bd/block_diagram/ip/block_diagram_rst_ps7_0_100M_0/block_diagram_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_rst_ps7_0_100M_0 || ORIG_REF_NAME==block_diagram_rst_ps7_0_100M_0}]

# IP: bd/block_diagram/ip/block_diagram_axi_gpio_0_1/block_diagram_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_axi_gpio_0_1 || ORIG_REF_NAME==block_diagram_axi_gpio_0_1}]

# IP: bd/block_diagram/ip/block_diagram_xbar_0/block_diagram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xbar_0 || ORIG_REF_NAME==block_diagram_xbar_0}]

# IP: bd/block_diagram/ip/block_diagram_auto_pc_0/block_diagram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_auto_pc_0 || ORIG_REF_NAME==block_diagram_auto_pc_0}]

# XDC: bd/block_diagram/block_diagram_ooc.xdc
